import { z } from 'zod';
import { SafeIdSchema } from './safeId';

export const MAP_TILE_SIZE = 32;
export const MAP_WORLD_WIDTH = 544;
export const MAP_COLUMNS = MAP_WORLD_WIDTH / MAP_TILE_SIZE;

const layerKind = z.enum([
  'deepBackdrop',
  'farGround',
  'groundBase',
  'terrainSurface',
  'terrainDetail',
  'airOccluder',
  'weather',
]);

export const TerrainCellSchema = z.object({
  x: z
    .number()
    .int()
    .min(0)
    .max(MAP_COLUMNS - 1),
  row: z.number().int().nonnegative(),
  tile: z.number().int().nonnegative(),
  /** Optional exact atlas frame for authored structures and landmark compositions. */
  frame: z.number().int().nonnegative().optional(),
  /** Optional adjacency mask generated by the Composer autotiler (Cardinal-16 or Blob-47). */
  variant: z.number().int().min(0).max(255).optional(),
});

const TerrainLayerRenderModeSchema = z.enum(['cells', 'tileSprite', 'compositedCells']);

export const TerrainLayerSchema = z
  .object({
    id: SafeIdSchema,
    name: z.string().min(1),
    kind: layerKind,
    scrollRatio: z.number().min(0.05).max(2),
    depth: z.number().int(),
    opacity: z.number().min(0).max(1).default(1),
    collisionAligned: z.boolean().default(false),
    visible: z.boolean().default(true),
    renderMode: TerrainLayerRenderModeSchema.default('cells'),
    materialTile: z.number().int().nonnegative().optional(),
    cells: z.array(TerrainCellSchema),
  })
  .superRefine((layer, ctx) => {
    if ((layer.renderMode === 'tileSprite' || layer.renderMode === 'compositedCells') && layer.materialTile === undefined) {
      ctx.addIssue({
        code: 'custom',
        path: ['materialTile'],
        message: `${layer.renderMode} layers require materialTile`,
      });
    }
    if (layer.renderMode === 'tileSprite' && layer.cells.length > 0) {
      ctx.addIssue({
        code: 'custom',
        path: ['cells'],
        message: 'tileSprite layers must not store explicit cells',
      });
    }
    if (layer.renderMode === 'compositedCells' && layer.cells.length === 0) {
      ctx.addIssue({
        code: 'custom',
        path: ['cells'],
        message: 'compositedCells layers require mask cells',
      });
    }
  });

export const TerrainMapSchema = z
  .object({
    formatVersion: z.literal('2.0'),
    id: SafeIdSchema,
    displayName: z.string().min(1),
    biomeId: SafeIdSchema,
    tileSize: z.literal(MAP_TILE_SIZE),
    worldWidth: z.literal(MAP_WORLD_WIDTH),
    rows: z.number().int().positive(),
    chunkRows: z.number().int().min(4).max(64).default(16),
    originWorldY: z.number(),
    layers: z.array(TerrainLayerSchema).min(1),
  })
  .superRefine((map, ctx) => {
    const ids = new Set<string>();
    map.layers.forEach((layer, li) => {
      if (ids.has(layer.id)) {
        ctx.addIssue({
          code: 'custom',
          path: ['layers', li, 'id'],
          message: `duplicate layer id "${layer.id}"`,
        });
      }
      ids.add(layer.id);
      if (layer.collisionAligned && layer.scrollRatio !== 1) {
        ctx.addIssue({
          code: 'custom',
          path: ['layers', li, 'scrollRatio'],
          message: 'collision-aligned layers must use scrollRatio 1',
        });
      }
      const cellKeys = new Set<string>();
      layer.cells.forEach((cell, ci) => {
        if (cell.row >= map.rows) {
          ctx.addIssue({
            code: 'custom',
            path: ['layers', li, 'cells', ci, 'row'],
            message: 'cell row exceeds map rows',
          });
        }
        const key = `${cell.x}:${cell.row}`;
        if (cellKeys.has(key)) {
          ctx.addIssue({
            code: 'custom',
            path: ['layers', li, 'cells', ci],
            message: `duplicate cell ${key}`,
          });
        }
        cellKeys.add(key);
      });
    });
  });

export const CorridorSampleSchema = z.object({
  worldY: z.number(),
  left: z.number().min(0).max(MAP_WORLD_WIDTH),
  right: z.number().min(0).max(MAP_WORLD_WIDTH),
});

export const TerrainCollisionSchema = z
  .object({
    formatVersion: z.literal('2.0'),
    id: SafeIdSchema,
    mapId: SafeIdSchema,
    contactDamage: z.number().nonnegative().default(20),
    lethalContact: z.boolean().default(false),
    corridor: z.object({
      id: SafeIdSchema,
      samples: z.array(CorridorSampleSchema).min(2),
      blocksPlayerProjectiles: z.boolean().default(true),
      blocksEnemyProjectiles: z.boolean().default(true),
    }),
  })
  .superRefine((collision, ctx) => {
    let prior = -Infinity;
    collision.corridor.samples.forEach((sample, i) => {
      if (sample.worldY <= prior) {
        ctx.addIssue({
          code: 'custom',
          path: ['corridor', 'samples', i, 'worldY'],
          message: 'samples must be strictly ordered by worldY',
        });
      }
      if (sample.right <= sample.left) {
        ctx.addIssue({
          code: 'custom',
          path: ['corridor', 'samples', i, 'right'],
          message: 'right must be greater than left',
        });
      }
      prior = sample.worldY;
    });
  });

export const RouteSetSchema = z
  .object({
    formatVersion: z.literal('2.0'),
    id: SafeIdSchema,
    mapId: SafeIdSchema,
    routes: z
      .array(
        z.object({
          id: SafeIdSchema,
          name: z.string().min(1),
          minimumRadius: z.number().positive(),
          samples: z
            .array(
              z.object({
                worldY: z.number(),
                centerX: z.number().min(0).max(MAP_WORLD_WIDTH),
                clearance: z.number().positive(),
              }),
            )
            .min(2),
        }),
      )
      .min(1),
  })
  .superRefine((routes, ctx) => {
    routes.routes.forEach((route, ri) => {
      let prior = -Infinity;
      route.samples.forEach((sample, si) => {
        if (sample.worldY <= prior) {
          ctx.addIssue({
            code: 'custom',
            path: ['routes', ri, 'samples', si, 'worldY'],
            message: 'samples must be strictly ordered by worldY',
          });
        }
        prior = sample.worldY;
      });
    });
  });

const gateObject = z.object({
  type: z.literal('gate'),
  id: SafeIdSchema,
  worldY: z.number(),
  x: z.number().min(0).max(MAP_WORLD_WIDTH),
  width: z.number().positive(),
  height: z.number().positive(),
  openingWidth: z.number().nonnegative(),
  initialState: z.enum(['open', 'closed']).default('closed'),
  damage: z.number().nonnegative().default(20),
});

const barrierObject = z.object({
  type: z.literal('barrier'),
  id: SafeIdSchema,
  worldY: z.number(),
  x: z.number().min(0).max(MAP_WORLD_WIDTH),
  width: z.number().positive(),
  height: z.number().positive(),
  hitPoints: z.number().positive(),
  creditValue: z.number().int().nonnegative().default(0),
  damage: z.number().nonnegative().default(20),
});

export const TerrainObjectSchema = z.discriminatedUnion('type', [
  gateObject,
  barrierObject,
]);
export const TerrainObjectSetSchema = z.object({
  formatVersion: z.literal('2.0'),
  id: SafeIdSchema,
  mapId: SafeIdSchema,
  objects: z.array(TerrainObjectSchema),
});

const BLOB47_MASK_KEY = /^(?:[0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])$/;

function normalizeBlob47Mask(mask: number): number {
  let normalized = mask & 0x0f;
  if ((mask & 16) !== 0 && (normalized & 1) !== 0 && (normalized & 2) !== 0)
    normalized |= 16;
  if ((mask & 32) !== 0 && (normalized & 2) !== 0 && (normalized & 4) !== 0)
    normalized |= 32;
  if ((mask & 64) !== 0 && (normalized & 4) !== 0 && (normalized & 8) !== 0)
    normalized |= 64;
  if ((mask & 128) !== 0 && (normalized & 8) !== 0 && (normalized & 1) !== 0)
    normalized |= 128;
  return normalized;
}

const VALID_BLOB47_MASKS = Array.from({ length: 256 }, (_, value) =>
  normalizeBlob47Mask(value),
).filter((value, index, values) => values.indexOf(value) === index);

const TerrainMetatileFramesSchema = z.object({
  columns: z.number().int().positive(),
  rows: z.number().int().positive(),
  frames: z.array(z.number().int().nonnegative()).min(1),
});

const TerrainFrameChoiceSchema = z.union([
  z.number().int().nonnegative(),
  z.array(z.number().int().nonnegative()).min(1).max(4),
]);

const TerrainVisualMaterialSchema = z.object({
  materialId: SafeIdSchema,
  baseFrames: z.array(z.number().int().nonnegative()).min(1),
  cardinalFrames: z
    .record(z.string().regex(/^(?:[0-9]|1[0-5])$/), z.number().int().nonnegative())
    .optional(),
  blob47Frames: z
    .record(z.string().regex(BLOB47_MASK_KEY), TerrainFrameChoiceSchema)
    .optional(),
  metatileFrames: TerrainMetatileFramesSchema.optional(),
  animationFrames: z.array(z.number().int().nonnegative()).default([]),
  animationFps: z.number().positive().optional(),
  synchronizedAnimation: z.boolean().default(false),
});

const TerrainPlaneSchema = z.object({
  materialId: SafeIdSchema,
  uri: z
    .string()
    .min(1)
    .refine((value) => !value.includes('..') && !value.startsWith('/'), {
      message: 'plane URI must be a relative project asset path',
    }),
  frameWidth: z.number().int().positive(),
  frameHeight: z.number().int().positive(),
  columns: z.number().int().positive(),
  rows: z.number().int().positive(),
  animationFrames: z.array(z.number().int().nonnegative()).min(1),
  animationFps: z.number().positive().default(1),
  driftX: z.number().default(0),
  driftY: z.number().default(0),
});

const RuntimeTerrainTilesetSchema = z
  .object({
    id: SafeIdSchema,
    displayName: z.string().min(1),
    uri: z
      .string()
      .min(1)
      .refine((value) => !value.includes('..') && !value.startsWith('/'), {
        message: 'tileset URI must be a relative project asset path',
      }),
    tileSize: z.literal(MAP_TILE_SIZE),
    columns: z.number().int().positive(),
    rows: z.number().int().positive(),
    materials: z.array(TerrainVisualMaterialSchema).min(1),
    planes: z.array(TerrainPlaneSchema).default([]),
  })
  .superRefine((tileset, ctx) => {
    const frameCount = tileset.columns * tileset.rows;
    const materialIds = new Set<string>();
    tileset.materials.forEach((material, materialIndex) => {
      if (materialIds.has(material.materialId)) {
        ctx.addIssue({
          code: 'custom',
          path: ['materials', materialIndex, 'materialId'],
          message: `duplicate visual material "${material.materialId}"`,
        });
      }
      materialIds.add(material.materialId);
      const frames = [
        ...material.baseFrames,
        ...(material.animationFrames ?? []),
        ...Object.values(material.cardinalFrames ?? {}),
        ...Object.values(material.blob47Frames ?? {}).flatMap((choice) =>
          Array.isArray(choice) ? choice : [choice],
        ),
        ...(material.metatileFrames?.frames ?? []),
      ];
      frames.forEach((frame) => {
        if (frame >= frameCount) {
          ctx.addIssue({
            code: 'custom',
            path: ['materials', materialIndex],
            message: `frame ${frame} exceeds ${frameCount - 1}`,
          });
        }
      });
      if (material.cardinalFrames) {
        for (let mask = 0; mask < 16; mask += 1) {
          if (material.cardinalFrames[String(mask)] === undefined) {
            ctx.addIssue({
              code: 'custom',
              path: ['materials', materialIndex, 'cardinalFrames', String(mask)],
              message: `Cardinal-16 mapping is missing mask ${mask}`,
            });
          }
        }
      }
      if (material.metatileFrames) {
        const expected = material.metatileFrames.columns * material.metatileFrames.rows;
        if (material.metatileFrames.frames.length !== expected) {
          ctx.addIssue({
            code: 'custom',
            path: ['materials', materialIndex, 'metatileFrames', 'frames'],
            message: `metatile frame count must equal ${expected}`,
          });
        }
      }
      if (material.blob47Frames) {
        for (const mask of VALID_BLOB47_MASKS) {
          if (material.blob47Frames[String(mask)] === undefined) {
            ctx.addIssue({
              code: 'custom',
              path: ['materials', materialIndex, 'blob47Frames', String(mask)],
              message: `Blob-47 mapping is missing canonical mask ${mask}`,
            });
          }
        }
        for (const key of Object.keys(material.blob47Frames)) {
          const mask = Number(key);
          if (!VALID_BLOB47_MASKS.includes(mask)) {
            ctx.addIssue({
              code: 'custom',
              path: ['materials', materialIndex, 'blob47Frames', key],
              message: `Blob-47 mapping contains non-canonical mask ${key}`,
            });
          }
        }
      }
      if ((material.animationFrames?.length ?? 0) > 0 && !material.animationFps) {
        ctx.addIssue({
          code: 'custom',
          path: ['materials', materialIndex, 'animationFps'],
          message: 'animated visual materials require animationFps',
        });
      }
    });
    const planeMaterialIds = new Set<string>();
    tileset.planes.forEach((plane, planeIndex) => {
      if (planeMaterialIds.has(plane.materialId)) {
        ctx.addIssue({
          code: 'custom',
          path: ['planes', planeIndex, 'materialId'],
          message: `duplicate plane material "${plane.materialId}"`,
        });
      }
      planeMaterialIds.add(plane.materialId);
      const frameCount = plane.columns * plane.rows;
      plane.animationFrames.forEach((frame) => {
        if (frame >= frameCount) {
          ctx.addIssue({
            code: 'custom',
            path: ['planes', planeIndex, 'animationFrames'],
            message: `plane frame ${frame} exceeds ${frameCount - 1}`,
          });
        }
      });
    });
  });

export const BiomeSchema = z
  .object({
    formatVersion: z.literal('1.0'),
    id: SafeIdSchema,
    displayName: z.string().min(1),
    backgroundColor: z.number().int().nonnegative(),
    materials: z.array(
      z.object({
        tile: z.number().int().nonnegative(),
  /** Optional exact atlas frame for authored structures and landmark compositions. */
  frame: z.number().int().nonnegative().optional(),
        id: SafeIdSchema,
        displayName: z.string().min(1),
        color: z.number().int().nonnegative(),
        edgeColor: z.number().int().nonnegative(),
        alpha: z.number().min(0).max(1).default(1),
        animated: z.boolean().default(false),
        collisionRole: z.enum(['none', 'solid', 'hazard']).default('none'),
      }),
    ),
    tileset: RuntimeTerrainTilesetSchema.optional(),
  })
  .superRefine((biome, ctx) => {
    const materialIds = new Set(biome.materials.map((material) => material.id));
    biome.tileset?.materials.forEach((visual, index) => {
      if (!materialIds.has(visual.materialId)) {
        ctx.addIssue({
          code: 'custom',
          path: ['tileset', 'materials', index, 'materialId'],
          message: `visual material "${visual.materialId}" is not declared by the biome`,
        });
      }
    });
    biome.tileset?.planes.forEach((plane, index) => {
      if (!materialIds.has(plane.materialId)) {
        ctx.addIssue({
          code: 'custom',
          path: ['tileset', 'planes', index, 'materialId'],
          message: `plane material "${plane.materialId}" is not declared by the biome`,
        });
      }
    });
  });

export const LevelPackageSchema = z.object({
  formatVersion: z.literal('2.0'),
  id: SafeIdSchema,
  levelId: SafeIdSchema,
  mapId: SafeIdSchema,
  collisionId: SafeIdSchema,
  routeSetId: SafeIdSchema,
  objectSetId: SafeIdSchema,
  biomeId: SafeIdSchema,
});

export type TerrainCellDef = z.infer<typeof TerrainCellSchema>;
export type TerrainMapDef = z.infer<typeof TerrainMapSchema>;
export type TerrainLayerDef = z.infer<typeof TerrainLayerSchema>;
export type TerrainCollisionDef = z.infer<typeof TerrainCollisionSchema>;
export type CorridorSample = z.infer<typeof CorridorSampleSchema>;
export type RouteSetDef = z.infer<typeof RouteSetSchema>;
export type TerrainObjectSetDef = z.infer<typeof TerrainObjectSetSchema>;
export type TerrainObjectDef = z.infer<typeof TerrainObjectSchema>;
export type BiomeDef = z.infer<typeof BiomeSchema>;
export type LevelPackageDef = z.infer<typeof LevelPackageSchema>;
